# Generated by Django 5.0.7 on 2024-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_register', '0002_remove_professeur_user_remove_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('1', '2IA'), ('2', 'IDSIT'), ('3', 'IDF'), ('4', 'BI&A'), ('5', 'GL'), ('6', 'GD'), ('7', 'SSI'), ('8', 'SSE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, choices=[('1', '2IA'), ('2', 'IDSIT'), ('3', 'IDF'), ('4', 'BI&A'), ('5', 'GL'), ('6', 'GD'), ('7', 'SSI'), ('8', 'SSE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_year',
            field=models.CharField(blank=True, choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
