# Generated by Django 5.0.7 on 2024-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_register', '0004_pdfupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
