# Generated by Django 5.0.7 on 2024-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_register', '0005_pdfupload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='sujet',
            field=models.CharField(default='default subject', max_length=255),
            preserve_default=False,
        ),
    ]
