# Generated by Django 5.0.7 on 2024-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_register', '0006_pdfupload_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('needs_modification', 'Needs Modification')], default='needs_modification', max_length=20),
        ),
    ]
